<div class="footer__top" id="pagetop">
  <img src="./assets/img/ic_top.png" alt="">
</div>
<div class="footer__menu">
  <h3 class="footer__tt">遠心分離機について</h3>
  <ul class="footer__service">
    <li>
      <a href="#">
        <img src="./assets/img/ft_img01.png" alt="">
        <dl>
          <dt>遠心分離機とは？</dt>
          <dd>What is a Centrifuge?</dd>
        </dl>
      </a>
    </li>
    <li>
      <a href="#">
        <img src="./assets/img/ft_img02.png" alt="">
        <dl>
          <dt>遠心分離機Q&A</dt>
          <dd>FAQ</dd>
        </dl>
      </a>
    </li>
    <li>
      <a href="#">
        <img src="./assets/img/ft_img03.jpg" alt="">
        <dl>
          <dt>カスタマイズについて</dt>
          <dd>Customization</dd>
        </dl>
      </a>
    </li>
    <li>
      <a href="#">
        <img src="./assets/img/ft_img04.png" alt="">
        <dl>
          <dt>カタログダウンロード</dt>
          <dd>Download</dd>
        </dl>
      </a>
    </li>
    <li>
      <a href="#">
        <img src="./assets/img/ft_img05.png" alt="">
        <dl>
          <dt>遠心分離機の選び方</dt>
          <dd>How to Choose</dd>
        </dl>
      </a>
    </li>
    <li>
      <a href="#">
        <img src="./assets/img/ft_img06.jpg" alt="">
        <dl>
          <dt>「遠心分離機の基礎知識」<br>冊子プレゼント</dt>
          <dd>Booklet Giveaway</dd>
        </dl>
      </a>
    </li>
    <li>
      <a href="#">
        <img src="./assets/img/ft_img07.png" alt="">
        <dl>
          <dt>YouTube動画</dt>
          <dd>YouTube</dd>
        </dl>
      </a>
    </li>
  </ul>
</div>
<div class="footer__customer">
  <div class="footer__row row">
    <h3 class="tt tt--white">CUSTOMER SUPPORT<span>お客様サポート</span></h3>
    <div class="footer__ct">
      <div class="footer__l">
        <dl>
          <dt>お電話でのお問い合わせ</dt>
          <dd>
            <ul>
              <li>
                <label>大阪(総合窓口)</label>
                <a class="ft__phone" href="tel:072-221-6622">072-221-6622</a>
                <span class="ft__fax">072-222-1921</span>
              </li>
              <li>
                <label>東京</label>
                <a class="ft__phone" href="tel:03-3553-8891">03-3553-8891</a>
                <span class="ft__fax">03-3553-0444</span>
              </li>
              <li>
                <label>富山</label>
                <a class="ft__phone" href="tel:076-495-8488">076-495-8488</a>
                <span class="ft__fax">076-495-8688</span>
              </li>
            </ul>
          </dd>
        </dl>
        <dl>
          <dt>機器の故障及び技術的なお問い合わせ</dt>
          <dd>
            <div class="ft__mobile">
              <a href="tel:072-232-3333">072-232-3333</a>
              <span>受付時間／平日 9:00～17:30</span>
            </div>
          </dd>
        </dl>
      </div>
      <div class="footer__r">
        <dl>
          <dt>dummy</dt>
          <dd>
            <div class="ft__btn"><a href="#">お問い合わせフォームはこちら</a></div>
            <span>※1営業日以内にて弊社担当者より折り返しご連絡いたします。</span>
          </dd>
        </dl>
      </div>
    </div>
  </div>
</div>
<div class="footer__main">
  <div class="footer__row row">
    <ul class="footer__banner">
      <li><a href="#"><img src="./assets/img/ft_banner01.png" alt=""></a></li>
      <li><a href="#"><img src="./assets/img/ft_banner02.png" alt=""></a></li>
      <li><a href="#"><img src="./assets/img/ft_banner03.png" alt=""></a></li>
      <li><a href="#"><img src="./assets/img/ft_banner04.png" alt=""></a></li>
    </ul>
    <div class="footer__gr">
      <div class="footer__col">
        <dl>
          <dt>松本機械販売株式会社</dt>
          <dd>〒590-0906</dd>
          <dd>堺市堺区三宝町6丁326番地</dd>
          <dd>TEL／072-221-6622（代表）</dd>
          <dd>FAX／072-222-1921</dd>
          <dd>製品に関するお問い合わせ TEL／072-221-6622</dd>
        </dl>
        <dl>
          <dt>松本機械製作所</dt>
          <dd>〒590-0906</dd>
          <dd>堺市堺区三宝町6丁326番地</dd>
          <dd>Tel　072-229-3388（代表）</dd>
          <dd>Fax　072-228-1751</dd>
        </dl>
      </div>
      <figure><img src="./assets/img/ft_img_df.png" alt=""></figure>
    </div>
  </div>
</div>
<div class="footer__copy">
  <div class="row">
    <p>&copy;2020 MATSUMOTO MACHINE SALES Co., Ltd. All rights Reserved.</p>
  </div>
</div>
