<div class="header__top">
  <div class="header__left">
    <h1><a href="./"><img src="./assets/img/logo.png" alt=""></a></h1>
  </div>
  <div class="header__right">
    <div id="menu_icon" class="menu_icon show_sp">
      <span class="menu_icon_in">
        <span class="menu-trigger">
          <span></span>
          <span></span>
          <span></span>
        </span>
      </span>
    </div>
    <div class="header__ct show_pc">
      <div class="header__banner"><a href="#"><img src="./assets/img/header_banner.png" alt=""></a></div>
      <div class="header__phone">
        <a href="tel:072-221-6622">072-221-6622</a>
        <span>受付時間／平日 9:00～17:30</span>
      </div>
      <p class="header__slg">初めて遠心分離機をご検討の<br>お客様もお気軽にご相談ください</p>
      <div class="header__gr">
        <div class="header__find">
          <div class="header__search">
            <input type="text" placeholder="ENHANCED BY Google">
            <button>検索</button>
          </div>
          <ul class="header__menu">
            <li><a href="#">カタログ</a></li>
            <li><a href="#">お問い合わせ</a></li>
          </ul>
        </div>
        <ul class="header__language">
          <li><a href="#">JP</a></li>
          <li><a href="#">EN</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<nav id="nav" class="header__nav">
  <div class="row">
    <ul class="header__sp">
      <li class="has_sub">
        <a href="/">トップ</a>
        <div class="header__smenu">
          <dl>
            <dt>製品選択一覧</dt>
            <dd><a href="#">製品カテゴリから探す</a></dd>
            <dd><a href="#">目的から探す</a></dd>
            <dd><a href="#">納入実績から探す</a></dd>
            <dd><a href="#">製品名から探す</a></dd>
          </dl>
        </div>
      </li>
      <li><a href="#">遠心分離機とは？</a></li>
      <li><a href="#">遠心分離機の選び方</a></li>
      <li><a href="/faq.html">遠心分離機Q&A</a></li>
      <li><a href="/custom.html">カスタマイズについて</a></li>
      <li><a href="/info.html">採用情報</a></li>
      <li class="has_sub">
        <a href="#">会社概要</a>
        <div class="header__smenu">
          <dl>
            <dt>会社概要一覧</dt>
            <dd><a href="#">会社概要</a></dd>
            <dd><a href="/strength.html">当社の強みについて</a></dd>
          </dl>
        </div>
      </li>
    </ul>
    <div class="header__phone show_sp">
      <a href="tel:072-221-6622">072-221-6622</a>
      <span>受付時間／平日 9:00～17:30</span>
    </div>
    <div class="header__gr show_sp">
      <div class="header__find">
        <div class="header__search">
          <input type="text" placeholder="ENHANCED BY Google">
          <button>検索</button>
        </div>
        <ul class="header__menu">
          <li><a href="#">カタログ</a></li>
          <li><a href="#">お問い合わせ</a></li>
        </ul>
      </div>
      <ul class="header__language">
        <li><a href="#">JP</a></li>
        <li><a href="#">EN</a></li>
      </ul>
    </div>
  </div>
</nav>